"use client"

import { useMemo, useState } from "react"
import { ClaimRecord } from "@/lib/types"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { cn } from "@/lib/utils"
import { ArrowLeft, CheckCircle2, CircleAlert, ClipboardList, Search, X, XCircle } from "lucide-react"

const styles = { approved: { label: "Agent approved", color: "bg-green-500/15 text-green-700 dark:text-green-400", icon: CheckCircle2 }, manual_review: { label: "Agent review needed", color: "bg-yellow-500/15 text-yellow-700 dark:text-yellow-400", icon: CircleAlert }, rejected: { label: "Agent rejected", color: "bg-red-500/15 text-red-700 dark:text-red-400", icon: XCircle } }

export function ClaimsPanel({ open, onOpenChange, claims }: { open: boolean; onOpenChange: (open: boolean) => void; claims: ClaimRecord[] }) {
  const [query, setQuery] = useState("")
  const [selected, setSelected] = useState<ClaimRecord | null>(null)
  const filtered = useMemo(() => claims.filter(c => `${c.claimId} ${c.employeeName} ${c.purpose} ${c.ticketId || ""}`.toLowerCase().includes(query.toLowerCase())), [claims, query])
  const grouped = useMemo(() => filtered.reduce((groups, c) => { const date = dateLabel(c.createdAt); (groups[date] ||= []).push(c); return groups }, {} as Record<string, ClaimRecord[]>), [filtered])
  if (!open) return null
  return <div className="fixed inset-0 z-50 bg-background/80 backdrop-blur-sm"><div className="fixed inset-y-0 right-0 flex w-full max-w-lg flex-col border-l border-border bg-background shadow-xl">
    <header className="flex items-center justify-between border-b border-border p-4"><div className="flex items-center gap-2"><ClipboardList className="h-5 w-5 text-primary" /><h2 className="text-lg font-semibold">Claims</h2><span className="text-sm text-muted-foreground">({claims.length} {claims.length === 1 ? "claim" : "claims"})</span></div><Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => onOpenChange(false)}><X className="h-4 w-4" /></Button></header>
    {selected ? <ClaimDetail claim={selected} onBack={() => setSelected(null)} /> : <><div className="border-b border-border p-4"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Search claims..." value={query} onChange={e => setQuery(e.target.value)} /></div></div><ScrollArea className="flex-1"><div className="p-4">{Object.keys(grouped).length ? Object.entries(grouped).map(([date, group]) => <div key={date} className="mb-6"><div className="mb-3 flex items-center gap-2"><span className="text-xs font-medium uppercase tracking-wider text-muted-foreground">{date}</span><div className="h-px flex-1 bg-border" /></div><div className="space-y-2">{group.map(claim => <ClaimRow key={claim.claimId} claim={claim} onClick={() => setSelected(claim)} />)}</div></div>) : <Empty text={query ? "No claims found matching your search" : "No submitted claims yet"} />}</div></ScrollArea></>}
  </div></div>
}

function ClaimRow({ claim, onClick }: { claim: ClaimRecord; onClick: () => void }) { const state = styles[claim.agentStatus]; const Icon = state.icon; return <button onClick={onClick} className="flex w-full items-start gap-3 rounded-lg p-3 text-left transition-colors hover:bg-accent"><div className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-full", state.color)}><Icon className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><h3 className="font-medium">{claim.claimId}</h3><span className="shrink-0 text-xs text-muted-foreground">{formatTime(claim.createdAt)}</span></div><p className="mt-1 truncate text-sm text-muted-foreground">{claim.employeeName} - {claim.purpose}</p><p className={cn("mt-1 text-xs font-medium", state.color.split(" ").slice(1).join(" "))}>{state.label}{claim.ticketId ? ` - ${claim.ticketId}` : ""}</p></div></button> }

function ClaimDetail({ claim, onBack }: { claim: ClaimRecord; onBack: () => void }) { const state = styles[claim.agentStatus]; const Icon = state.icon; return <ScrollArea className="flex-1"><div className="space-y-5 p-4"><Button variant="ghost" size="sm" className="-ml-2" onClick={onBack}><ArrowLeft className="mr-1 h-4 w-4" /> All claims</Button><div><h3 className="text-xl font-semibold">{claim.claimId}</h3><p className="text-sm text-muted-foreground">Submitted {new Date(claim.createdAt).toLocaleString()}</p></div><div className={cn("inline-flex items-center gap-2 rounded-full px-3 py-1 text-sm font-medium", state.color)}><Icon className="h-4 w-4" />{state.label}</div><section className="grid gap-3 rounded-lg border p-4 sm:grid-cols-2"><Detail label="Employee" value={claim.employeeName} /><Detail label="Employee ID / email" value={claim.employeeContact} /><Detail label="Department" value={claim.department} /><Detail label="Business purpose" value={claim.purpose} /><Detail label="Trip" value={`${claim.startDate} - ${claim.endDate}`} /><Detail label="Destination" value={claim.destination} /></section><section className="rounded-lg border p-4"><h4 className="font-semibold">Expenses submitted by user</h4>{claim.expenses.length ? claim.expenses.map((item, index) => <div key={index} className="mt-3 border-t pt-3 text-sm"><p className="font-medium">{item.category} - ${item.amount.toFixed(2)}</p><p className="text-muted-foreground">{item.description} · {item.date} · Receipt: {item.receiptAttached ? "Attached" : "Missing"}</p></div>) : <p className="mt-2 text-sm text-muted-foreground">Detailed line items were not available in the earlier chat submission.</p>}<p className="mt-3 text-right font-medium">Total claimed: ${claim.total.toFixed(2)}</p></section><section className="rounded-lg border p-4"><h4 className="font-semibold">Action taken by agent</h4><p className="mt-1 text-sm text-muted-foreground">{claim.agentAction}</p>{claim.ticketId && <p className="mt-2 text-sm font-medium text-green-700 dark:text-green-400">Ticket: {claim.ticketId} · Eligible: ${claim.reimbursable.toFixed(2)}</p>}{claim.rejectionReasons.length > 0 && <div className="mt-3 rounded-md bg-red-500/10 p-3 text-sm text-red-700 dark:text-red-400"><p className="font-medium">Reason for rejection</p><ul className="mt-1 list-disc pl-5">{claim.rejectionReasons.map(reason => <li key={reason}>{reason}</li>)}</ul></div>}</section><section className="rounded-lg border p-4"><h4 className="font-semibold">Action needed by reviewer</h4><p className="mt-1 text-sm text-muted-foreground">{claim.reviewerAction}</p></section></div></ScrollArea> }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-0.5 text-sm font-medium">{value || "Not provided"}</p></div> }
function Empty({ text }: { text: string }) { return <div className="py-12 text-center text-sm text-muted-foreground"><ClipboardList className="mx-auto mb-3 h-10 w-10 opacity-30" />{text}</div> }
function formatTime(timestamp: number) { return new Date(timestamp).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" }) }
function dateLabel(timestamp: number) { const days = Math.floor((Date.now() - timestamp) / 86400000); return days === 0 ? "Today" : days === 1 ? "Yesterday" : new Date(timestamp).toLocaleDateString("en-US", { month: "short", day: "numeric" }) }
